### ISSUE TITLE
go-bindata tool missing in third_party/go

### ISSUE THREAD

**Issue by jasiekmarc** [thought-machine/pleasings#23]
`go_bindata` rule depends on _go-bindata_ tool 
https://github.com/thought-machine/pleasings/blob/e388718147b053ca242cd65ca33068da67858141/go/go_bindata.build_defs#L18
This tool is however missing from the relevant BUILD file (https://github.com/thought-machine/pleasings/blob/master/third_party/go/BUILD).

**Comment by peterebden** [comment]
Thanks, have added it!
