### ISSUE TITLE
//python:requirements fails as of plz v15.8.0

### ISSUE THREAD

**Issue by afterthought** [thought-machine/pleasings#60]
To reproduce:

    ./pleasew test //python/test:requirements_test

If you edit .plzconfig and set the version as 15.7.1 the test passes. 15.8.0 causes the test to fail.

Seems like it is this PR that caused the regression:

https://github.com/thought-machine/please/pull/1346

The gist of that PR is that python -m pip is favored over /usr/bin/pip3.  I can make the test pass by hardcoding /usr/bin/pip3 for the piptool, but I don't know please well enough to know the proper fix.

**Comment by Tatskaari** [comment]
Sorry for the slow reply. I think I've fixed this now though. Let me know if you have any additional issues.
