### ISSUE TITLE
Feature Request: Pleasings for helm charts

### ISSUE THREAD

**Issue by mrsauravsahu** [thought-machine/pleasings#82]
# Current Situation

I'm currently using the k8s pleasing to generate the yaml configs.

# Goal:

Use pleasings to generate my helm-charts directory as a bin & install/uninstall helm charts through `plz`. I'm trying to figure out to what's the best way this new build definition should look like.

I assume: 
- I create a template helm chart, add a `BUILD` file to generate the base helm-chart template
- Use this to generate helm charts for my different services but still being able to override envVar, values etc.
- The `BUILD` per service should have outputs like `_upgrade` (this should be able to read extra envVar, values to override in the charts), `_uninstall`(which will remove the chart) - and these will call internal helm commands.

I have barely begun working on this and would love to hear others' thoughts on an approach.

**Comment by mrsauravsahu** [comment]
This is the sample project in which I've setup please.build - https://github.com/mrsauravsahu/template-monorepo

**Comment by afterthought** [comment]
Looks like a couple of months have passed. I have a helm build def that I have been using. I have had it embedded in my project, but need to pull it out now. I was going to add it to a fork of pleasings, but wasn't sure it would make for a good PR. It works pretty well, but I think it would benefit from some maintainer attention.

**Comment by mrsauravsahu** [comment]
Awesome! Please open up a PR, I can try it out through your fork!

**Comment by afterthought** [comment]
Sorry for the delay. I think I have notifications turned off. Here it is: #90
