### ISSUE TITLE
Docs: How to use dockerfile with multiple `FROM` statements

### ISSUE THREAD

**Issue by mrsauravsahu** [thought-machine/pleasings#87]
I'm trying to build a package which has multiple FROM statements.

Refer https://github.com/mrsauravsahu/souvenirs/blob/main/srv/gateway/prod.dotnet-webapi.dockerfile for the exact dockerfile

Is this not supported or am I not able to find the right docs? Would be interested in implementing this if not available too!

**Comment by Tatskaari** [comment]
Sorry, I thought I responded. I would expect this to work out of the box. Please generates a `.sh` script that calls `docker build` on the docker file, so as long as that works, I can't see why this wouldn't. Have you found that it doesn't work? How does it fail?

**Comment by mrsauravsahu** [comment]
I can't seem to reproduce this anymore. Will reopen if I run into it again.
