### ISSUE TITLE
Feature Request: Pleasings for docker compose

### ISSUE THREAD

**Issue by hardishw** [thought-machine/pleasings#94]
I can build and run docker images but it would be great if I could run the entire build locally with just please, similar to how the docker files are built.

**Comment by Tatskaari** [comment]
Sorry for the slow response. Unfortunately, we don't use docker-compose so have no big interest in supporting them as first party rules. If you'd like to extend Please with a plugin, you can find some examples here:

https://github.com/please-build/please-rules

I'll close this issue for now but please let me know if you make any progress here.
